steps:
#Build and push the image --> Cloud Build Service Account, Service Account User & Viewer Role
- name: 'hashicorp/terraform'
  args: ['init']

- name: 'hashicorp/terraform'
  args: ['apply', '-auto-approve']
  #args: ['apply', '-auto-approve', '-destroy']

options:
  logging: CLOUD_LOGGING_ONLY
